name: Info submitted

on:
  issues:
    types: [opened, edited]

jobs:
  handle-submission:
    name: Handle new submission
    if: contains(github.event.issue.labels.*.name, 'update info')
    runs-on: ubuntu-latest
    
    steps:
    - name: GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache golang modules
      uses: actions/cache@v2
      with:
        path: |
          ~/go
        key: ${{ runner.os }}-go-v1
        restore-keys: |
          ${{ runner.os }}-go-
    
    - name: Install json-schema validator
      run: go get neilpa.me/yajsv

    - name: Update project and contracts
      env:
        ISSUE_BODY: ${{ github.event.issue.body }}
      run: |
        echo -e "$ISSUE_BODY" | python scripts/handle-submission.py

    - name: Mark as added
      run: git add -N .

    - name: Test submission
      run: scripts/test.sh
      env:
        GIT_BASE: main

    - name: Create pull request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: "Update info from #${{github.event.issue.number}}"
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: info/issue-${{github.event.issue.number}}
        delete-branch: true
        title: 'Update info from #${{github.event.issue.number}}'
        body: |
          Fixes #${{github.event.issue.number}}
        labels: |
          update-info
        draft: false

